- name: Create compose app directory
  become: true
  file:
    path: /root/app
    state: directory
    mode: "0755"

- name: Deploy app docker-compose
  become: true
  copy:
    src: "{{ playbook_dir }}/../compose/app/docker-compose.yml"
    dest: /root/app/docker-compose.yml
    mode: "0644"

- name: Start/Update stack
  become: true
  args:
    chdir: /root/app
  shell: docker compose up -d
