- name: Create compose app directory
  file:
    path: /opt/app
    state: directory
    mode: '0755'
  become: true

- name: Deploy app docker-compose
  copy:
    src: "{{ playbook_dir }}/../../compose/app/docker-compose.yml"
    dest: /opt/app/docker-compose.yml
    mode: '0644'
  become: true

- name: Start/Update stack
  command: docker compose -f /opt/app/docker-compose.yml up -d
  become: true
